[package]
name = "rust_learn_task_manager"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.188"
serde_derive = "1.0.188"
bincode = "1.3.3"
